[[SoapyHackRF]]
arch = "aarch64"
git-tree-sha1 = "a0da037acaaab2203e4ff48e4033bea474c7992c"
os = "macos"

    [[SoapyHackRF.download]]
    sha256 = "5248980304ce5d74a27e18d88531b0fad77c8bc14f9ddbe2a8d6de09c7536fe5"
    url = "https://github.com/JuliaBinaryWrappers/SoapyHackRF_jll.jl/releases/download/SoapyHackRF-v0.3.4+0/SoapyHackRF.v0.3.4.aarch64-apple-darwin.tar.gz"
[[SoapyHackRF]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68aeac5a7b8c50325174ca1de5a1ae8f4509ab54"
libc = "glibc"
os = "linux"

    [[SoapyHackRF.download]]
    sha256 = "dc615a8769a1d31493c696450271686e19511cec9c68d8bf993b195ca126127f"
    url = "https://github.com/JuliaBinaryWrappers/SoapyHackRF_jll.jl/releases/download/SoapyHackRF-v0.3.4+0/SoapyHackRF.v0.3.4.aarch64-linux-gnu-cxx11.tar.gz"
[[SoapyHackRF]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0038148df2ed5cf9612b535b922f48ac5b850a2a"
libc = "musl"
os = "linux"

    [[SoapyHackRF.download]]
    sha256 = "43b91c971b77398be7fb7e67d606dd5958f23b0b9a6ef9bfbf78f877de1e8da1"
    url = "https://github.com/JuliaBinaryWrappers/SoapyHackRF_jll.jl/releases/download/SoapyHackRF-v0.3.4+0/SoapyHackRF.v0.3.4.aarch64-linux-musl-cxx11.tar.gz"
[[SoapyHackRF]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c838e1d316252cde1043ec1103385c4b00ba5d92"
libc = "glibc"
os = "linux"

    [[SoapyHackRF.download]]
    sha256 = "ca67877dad54bfb9302126ac0f6d0cac9941092b939cfe36804ae8d5a8ac83f3"
    url = "https://github.com/JuliaBinaryWrappers/SoapyHackRF_jll.jl/releases/download/SoapyHackRF-v0.3.4+0/SoapyHackRF.v0.3.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SoapyHackRF]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "899c4bc689c1cf605eef9646cac314509403e423"
libc = "musl"
os = "linux"

    [[SoapyHackRF.download]]
    sha256 = "196b50090bbe65ab5d30176922f3751f000ec6e68f68cb0ada815c7311f3d73f"
    url = "https://github.com/JuliaBinaryWrappers/SoapyHackRF_jll.jl/releases/download/SoapyHackRF-v0.3.4+0/SoapyHackRF.v0.3.4.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SoapyHackRF]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7a78ffa64be585c29488e6a82e591d027e75651"
libc = "glibc"
os = "linux"

    [[SoapyHackRF.download]]
    sha256 = "5e6eff6cb37660a7fd7921977dfe67687faceaea50c3529980ed89560f0f3e36"
    url = "https://github.com/JuliaBinaryWrappers/SoapyHackRF_jll.jl/releases/download/SoapyHackRF-v0.3.4+0/SoapyHackRF.v0.3.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SoapyHackRF]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f7b174e3ba3af2fb330ae6da658b511d91f79f8"
libc = "musl"
os = "linux"

    [[SoapyHackRF.download]]
    sha256 = "7017fa5655af65cc1a6f7a2ccd03100c6426e57a274ddc4acf5126e13613915b"
    url = "https://github.com/JuliaBinaryWrappers/SoapyHackRF_jll.jl/releases/download/SoapyHackRF-v0.3.4+0/SoapyHackRF.v0.3.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SoapyHackRF]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0d06a3279b4bbb16554e828604ad7f394f1ac26"
libc = "glibc"
os = "linux"

    [[SoapyHackRF.download]]
    sha256 = "60c2076d3f29424cba6b1a128a786fa6c691894aed3ee760c5e9784485ac558d"
    url = "https://github.com/JuliaBinaryWrappers/SoapyHackRF_jll.jl/releases/download/SoapyHackRF-v0.3.4+0/SoapyHackRF.v0.3.4.i686-linux-gnu-cxx11.tar.gz"
[[SoapyHackRF]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41c9434e1882981207f8d18445533b34de22bef7"
libc = "musl"
os = "linux"

    [[SoapyHackRF.download]]
    sha256 = "c9e86303b700179469b802395745e947b3414e84bf059a66a1fb137636c399d7"
    url = "https://github.com/JuliaBinaryWrappers/SoapyHackRF_jll.jl/releases/download/SoapyHackRF-v0.3.4+0/SoapyHackRF.v0.3.4.i686-linux-musl-cxx11.tar.gz"
[[SoapyHackRF]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46d9ea63c2ee713558256c1581c3418ad025df8c"
os = "windows"

    [[SoapyHackRF.download]]
    sha256 = "dd9b223e7fc38c3aae947b0e7e22c5c98a703c3281edcd755913e12b3b148633"
    url = "https://github.com/JuliaBinaryWrappers/SoapyHackRF_jll.jl/releases/download/SoapyHackRF-v0.3.4+0/SoapyHackRF.v0.3.4.i686-w64-mingw32-cxx11.tar.gz"
[[SoapyHackRF]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b7b7c1074e525301a870e0e5fb7254edd38ba1b"
libc = "glibc"
os = "linux"

    [[SoapyHackRF.download]]
    sha256 = "1a2de2efbb022669edf6439228e56742ccd05075aa2c137dd701ffe1e6339173"
    url = "https://github.com/JuliaBinaryWrappers/SoapyHackRF_jll.jl/releases/download/SoapyHackRF-v0.3.4+0/SoapyHackRF.v0.3.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SoapyHackRF]]
arch = "x86_64"
git-tree-sha1 = "9220c4891fd7dbb5415bad08ceba6bfd87530ccb"
os = "macos"

    [[SoapyHackRF.download]]
    sha256 = "45e744ffe78a18d8053065d209dcb8dfbd0fd001fea0b2202761b43a4b1f8030"
    url = "https://github.com/JuliaBinaryWrappers/SoapyHackRF_jll.jl/releases/download/SoapyHackRF-v0.3.4+0/SoapyHackRF.v0.3.4.x86_64-apple-darwin.tar.gz"
[[SoapyHackRF]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01056b9a67a098acd77152b6587af462ec44445e"
libc = "glibc"
os = "linux"

    [[SoapyHackRF.download]]
    sha256 = "26d35c84a07c75285bf374bbc360412107764b8a13b913c526005ae5f5200b31"
    url = "https://github.com/JuliaBinaryWrappers/SoapyHackRF_jll.jl/releases/download/SoapyHackRF-v0.3.4+0/SoapyHackRF.v0.3.4.x86_64-linux-gnu-cxx11.tar.gz"
[[SoapyHackRF]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ab4d42b52df0f8792831c5e33b83bf112342cbc"
libc = "musl"
os = "linux"

    [[SoapyHackRF.download]]
    sha256 = "c1d6beec1c9211346cda18987ef159b9725d49ddbebb4130b6eb13d5130e5854"
    url = "https://github.com/JuliaBinaryWrappers/SoapyHackRF_jll.jl/releases/download/SoapyHackRF-v0.3.4+0/SoapyHackRF.v0.3.4.x86_64-linux-musl-cxx11.tar.gz"
[[SoapyHackRF]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "644fc5bf73459a8a130c47ebcaeb87cbd4381217"
os = "windows"

    [[SoapyHackRF.download]]
    sha256 = "5bdb5e67047230d535bb55d68bbf7420e1819c156d53f8743246b3bf3ef08aaa"
    url = "https://github.com/JuliaBinaryWrappers/SoapyHackRF_jll.jl/releases/download/SoapyHackRF-v0.3.4+0/SoapyHackRF.v0.3.4.x86_64-w64-mingw32-cxx11.tar.gz"
