# Autogenerated wrapper script for SoapyHackRF_jll for aarch64-apple-darwin
export libHackRFSupport

using hackrf_jll
using soapysdr_jll
JLLWrappers.@generate_wrapper_header("SoapyHackRF")
JLLWrappers.@declare_library_product(libHackRFSupport, "libHackRFSupport.dylib")
function __init__()
    JLLWrappers.@generate_init_header(hackrf_jll, soapysdr_jll)
    JLLWrappers.@init_library_product(
        libHackRFSupport,
        "lib/SoapySDR/modules0.8/libHackRFSupport.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
