# Autogenerated wrapper script for SoapyHackRF_jll for i686-w64-mingw32-cxx11
export libHackRFSupport

using hackrf_jll
using soapysdr_jll
JLLWrappers.@generate_wrapper_header("SoapyHackRF")
JLLWrappers.@declare_library_product(libHackRFSupport, "libHackRFSupport.dll")
function __init__()
    JLLWrappers.@generate_init_header(hackrf_jll, soapysdr_jll)
    JLLWrappers.@init_library_product(
        libHackRFSupport,
        "bin\\libHackRFSupport.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
